### PR TITLE
Implement `<record>.{select,drop}_matching(<pattern>)`

### PR DESCRIPTION
**Pull request by dominiklohmann**
This allows for bulk-moving fields in a recod that match a certain pattern. For example:

```
let $pattern = "^audit-"
this = {
  audit: this.select_matching($pattern),
  ...this.drop_matching($pattern),
}
```

### CODE REVIEW

**Review by mavam — COMMENTED** [review]
Cool use of zipping through the array-type pairs. Can you add some tests?

**Comment by dominiklohmann** [comment]
> EDIT: I would also remove the `_matching` suffix.

There's a potential ambiguity with `select` and `drop` as functions that behave similar to our current operators when wanting to specify fields that contain characters that may not appear in identifiers. I would prefer not to do this for now.

> Can you add some tests?

I'll add some.

**Comment by mavam** [comment]
> > EDIT: I would also remove the `_matching` suffix.
> 
> There's a potential ambiguity with `select` and `drop` as functions that behave similar to our current operators when wanting to specify fields that contain characters that may not appear in identifiers. I would prefer not to do this for now.

Can you provide an example for such an ambiguity? I don't see it. But I'd leave this part to  @jachris anyway.

> > Can you add some tests?
> 
> I'll add some.

LGTM.

**Comment by dominiklohmann** [comment]
> Can you provide an example for such an ambiguity? I don't see it.

In `this.select(foo, bar, "field with spaces")`, is `"field with spaces"` a pattern or a field?

**Comment by jachris** [comment]
The problem is also that we do not really have a concrete design for a `.select()` method yet. So I find it hard to say whether it takes selectors, strings, whatever... But I agree that we probably don't want to constraint our solution space prematurely, so unless we come up with a design for "normal-mode" select, I'd agree that giving it a different name is better.

**Review by jachris — APPROVED** [review]
This worked great in my testing. We already discussed the naming a bit, I think this is fine for now. Might change later, we'll see.

**Pull request merged**
