### PR TITLE
Modernize CAF usage in `cache.cpp`

### PR DESCRIPTION
**Pull request by dominiklohmann**
Trying to learn how to use the new tools from CAF on a small example.

### CODE REVIEW

**Review by mavam — APPROVED** [review]
Approving as-is, as it's mostly a syntactic change.

If CI passes, this should be fine. However, the context plugin fails.

**Comment by dominiklohmann** [comment]
> However, the context plugin fails.

I think this is unrelated. @tobim had this once before during development of the CAF PR, but we couldn't reproduce it. We need to keep an eye on this in the current release cycle.

**Comment by dominiklohmann** [comment]
If I read the stacktrace correctly then it is coming from here: https://github.com/tenzir/tenzir/blob/c3998fa189917af7f9bad8f52953f60b590dd2c3/libtenzir/src/index.cpp#L1136-L1144

**Comment by dominiklohmann** [comment]
> If I read the stacktrace correctly then it is coming from here:

... and this also makes sense. The importer gets started after the index, so if the delta between the two being started is more than the metrics interval then we crash here. In the CAF version we were on previously sending to a nullptr was a no-op, now it runs into an assertion failure. I'll sneak in a fix.

**Pull request merged**
