### PR TITLE
Make `str.length()` return number of UTF8 code points

### PR DESCRIPTION
**Pull request by dominiklohmann**
This fixes situations like this:

```
// tql2
from {}
len = "😅".length()
```

Before this change, `len` was `4`. Now, it correctly is set to `1`, counting the number of grapheme clusters.

### CODE REVIEW

**Comment by raxyte** [comment]
I think the initial title was correct. That function counts UTF8 code-points instead of grapheme clusters. For example,
```
// tql2
from {}
len1 = "😅".length()
len2 = "é".length()
len3 = "é".length() // seemingly identical
```

**Comment by dominiklohmann** [comment]
> I think the initial title was correct.

That's a good catch, thank you. So much for ChatGPT telling me Arrow was counting grapheme clusters, I should've verified. 

We'll have to think about what we wanna do, if there's no good built-in support in Arrow then it's probably not worth spending the time, so I think we might want to stick with operating on code points for now.

**Comment by jachris** [comment]
I read a few articles and looked at what other languages or relevant standards like OCSF do here. My recommendation for now would be to add functions where the name explicitly indicates whether the functions returns number of bytes/number of codepoints/number of extended grapheme clusters. After getting some more experience with how these are used, we can think about what the "generic" length would be and potentially deprecate the long name for it.

**Comment by jachris** [comment]
Superseded by #4525.

**Pull request closed without merging**
