### PR TITLE
Add back `exporter.shipped` metric

### PR DESCRIPTION
**Pull request by dominiklohmann**
This adds the value `exporter.shipped` back to `tenzir-ctl export` based on request from @satta. Note that the feature is deprecated and due for removal in the future, with the `export` operator already being a superior replacement to the `tenzir-ctl export` command.

I did not test this, as we no longer are able to easily test metrics in this part of the code base, so I'd like to ask @satta to review this manually.

### CODE REVIEW

**Comment by satta** [comment]
Looks good, will test here, thanks. Let's hope I can get the version of Tenzir I build from source to not segfault on startup this time...

**Comment by dominiklohmann** [comment]
> FYI I needed to do:

You probably want to use `state.self_ptr->state.accountant` without the capture instead to avoid a very unlikely race condition on shutdown. But it doesn't matter for testing. It's a bit stupid to have to go through this, but then again, this is code that only exists to bridge between the old command-based and the new operator-based interfaces.

**Comment by dominiklohmann** [comment]
I locally verified that we emit metrics now with this change. @tobim, can you take a look at this?

**Comment by satta** [comment]
Interestingly I get various metrics entries now for one query:
```
{"ts": "2023-11-01T21:47:09.549167", "version": "v4.3.0-140-ge4c9341587-dirty", "actor": "exporter", "key": "exporter.shipped", "value": 9.0, "metadata": {"query": "00000000-0000-0000-0000-000000000000"}}
{"ts": "2023-11-01T21:47:09.549415", "version": "v4.3.0-140-ge4c9341587-dirty", "actor": "exporter", "key": "exporter.shipped", "value": 90.0, "metadata": {"query": "00000000-0000-0000-0000-000000000000"}}
{"ts": "2023-11-01T21:47:09.549655", "version": "v4.3.0-140-ge4c9341587-dirty", "actor": "exporter", "key": "exporter.shipped", "value": 30.0, "metadata": {"query": "00000000-0000-0000-0000-000000000000"}}
{"ts": "2023-11-01T21:47:09.549913", "version": "v4.3.0-140-ge4c9341587-dirty", "actor": "exporter", "key": "exporter.shipped", "value": 308.0, "metadata": {"query": "00000000-0000-0000-0000-000000000000"}}
{"ts": "2023-11-01T21:47:09.550179", "version": "v4.3.0-140-ge4c9341587-dirty", "actor": "exporter", "key": "exporter.shipped", "value": 8499.0, "metadata": {"query": "00000000-0000-0000-0000-000000000000"}}
{"ts": "2023-11-01T21:47:09.558453", "version": "v4.3.0-140-ge4c9341587-dirty", "actor": "exporter", "key": "exporter.shipped", "value": 804.0, "metadata": {"query": "00000000-0000-0000-0000-000000000000"}}
{"ts": "2023-11-01T21:47:09.566499", "version": "v4.3.0-140-ge4c9341587-dirty", "actor": "exporter", "key": "exporter.hits.runtime", "value": 46.392483, "metadata": {"query": "00000000-0000-0000-0000-000000000000"}}
{"ts": "2023-11-01T21:47:09.566735", "version": "v4.3.0-140-ge4c9341587-dirty", "actor": "exporter", "key": "exporter.shipped", "value": 260.0, "metadata": {"query": "00000000-0000-0000-0000-000000000000"}}
```
for
```
$ ./bin/tenzir-ctl -e localhost:42000 export -n 1000 json
[22:47:09.511] client connects to localhost:42000 (::1)
[22:47:09.512] client connected to node at localhost:42000
[22:47:09.868] sink received first result with a latency of 358.75ms
...
[22:47:14.793] sink reached limit of 1000 events
[22:47:14.793] sink processed 1000 events at a rate of 203 events/sec in 4.92s
[22:47:14.794] sink reached limit of 1000 events
[22:47:14.794] sink processed 0 events at a rate of 0 events/sec in 189.0ns
[22:47:14.794] sink reached limit of 1000 events
[22:47:14.794] sink processed 0 events at a rate of 0 events/sec in 186.0ns
[22:47:14.794] sink processed 0 events at a rate of 0 events/sec in 0.0ns

```

**Comment by dominiklohmann** [comment]
I pushed a small commit to this branch that changes it so that we send out the metric only once at the very end.

**Comment by satta** [comment]
Thanks!

**Review by tobim — APPROVED** [review]

**Pull request merged**
