### PR TITLE
Enable transparent decompression for single file inputs

### PR DESCRIPTION
**Pull request by tobim**
This PR replaces the IO path in the `file` loader with API functions provided by libarchive. This allows command line invocations like
```
vast -q exec 'from - read json | write json to stdout' < vast/integration/data/json/conn.log.json.gz
```
The other file loading variations work accordingly.

This currently comes at the expense of the `timeout` and `following` options, which need to be brought back in a libarchive specific way.
Doing so may be possible with a custom implementation for `archive_read_set_read_callback`, but that needs to be verified.

### CODE REVIEW

**Comment by tobim** [comment]
> This currently comes at the expense of the timeout and following options, which need to be brought back in a libarchive specific way.

I looked into this and learned that `timeout` isn't possible. While you can provide your own IO callbacks there is simply no way to signal "call me later" to the caller. Once we return 0 bytes the library will switch to the finalization routine.

My intuition is to remove `timeout` and avoid buffering anything in between calls to `read` in the operator.

**Comment by dominiklohmann** [comment]
> My intuition is to remove `timeout` and avoid buffering anything in between calls to `read` in the operator.

Doesn't sound like a good idea to me because this will introduce hangs on shutdown, and also increase the latency when receiving very small packets over a network. We have the read timeout for a very good reason.

Did you consider making this feature explicit instead as a bytes to bytes transformation operator called `decompress`?

**Comment by tobim** [comment]
> this will introduce hangs on shutdown

In what situation? An operator that does IO should be in it's own thread, and `read` is cancellable, so the termination code path can take care of it.

> and also increase the latency when receiving very small packets over a network

I don't understand, can you elaborate?

> Did you consider making this feature explicit instead as a bytes to bytes transformation operator called `decompress`?

I did, but that makes for a worse UX. Why should we force the user to provide information that we can infer?

**Comment by tobim** [comment]
This is now obsolete. The functionality has been implemented with the explicit `decompress` operator instead #3443.

**Pull request closed without merging**
