### PR TITLE
Allow unsafe pipelines on the demo node

### PR DESCRIPTION
**Pull request by tobim**

### CODE REVIEW

**Review by mavam — APPROVED** [review]

**Review by lava — COMMENTED** [review]
I think it makes more sense to add this variable to the service definition, so we can override it for specific demo nodes if desired.

**Comment by tobim** [comment]
> I think it makes more sense to add this variable to the service definition, so we can override it for specific demo nodes if desired.

Agreed, that would be better.  Can you open a PR for that?

**Comment by lava** [comment]
> Can you open a PR for that?

https://github.com/tenzir/event-horizon/pull/1750

**Comment by tobim** [comment]
This is solved somewhere else in a more flexible way.

**Pull request closed without merging**
